### ISSUE TITLE
Transactional doesn't work in private module when exposing the interface instead of the implementation

### ISSUE THREAD

**Issue by MirkoRossini** [mybatis/guice#81] opened 2016-09-29 13:37 UTC
See this [gist](https://gist.github.com/MirkoRossini/e6d5eb91f09d5989cb5a60c54998c272).

This main fails at this point:

`Exception in thread "main" java.lang.RuntimeException: Not transactional
    at com.mirkorossini.transactionaltest.Test.testTransactional(Test.java:51)
    at com.mirkorossini.transactionaltest.Test.main(Test.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)`

Notice that it only happen if I expose the SqlSessionManager explicitely, and only if I bind the interface instead of the implementation directly.

I also explain the issue more extensively  [here](http://geekyjournal.blogspot.com/2016/09/mybatis-guice-and-transactional_28.html).

**Comment by jeffgbutler** [comment] 2016-09-29 13:49
It sounds like you have stumbled upon a fairly well know bug/feature in Guice:

https://github.com/google/guice/issues/722

Take a look to verify, but if it's the same issue then there's nothing we can do about it - that's the way Guice works.

**Comment by christianpoitras** [comment] 2016-09-29 13:59
This is the most bizarre bug of Guice I would say. Private modules work in a really weird way when it comes to interceptors.

The problem is that Guice will not always instantiate an object the way you think it should. Just in time binding with private modules is bad. And unexpected Just in time binding is the worst.
Often, when Guice should instantiate an object in a private module, it will instantiate it from the private's module parent to make the binding available to the largest amount of classes. This will break any interceptors defined in the private module.
There are tricks that can be used to force Guice to instantiate the object in the private module (through bind and expose methods), but this may results in exceptions being thrown.

Using requireExplicitBindings() is probably the only way to make this safer.

**Comment by MirkoRossini** [comment] 2016-09-29 14:11
Thanks for the quick responses, looks like it's precisely my issue. Good to know

**Comment by vaibhavmagarwal** [comment] 2016-09-30 07:29
Hi,

In the [example](https://gist.github.com/MirkoRossini/e6d5eb91f09d5989cb5a60c54998c272) that @MirkoRossini gave, why are interceptors not applied *only* when the SqlSessionManager (instance variable) is exposed explicitely? The interceptors are applied when SqlSessionManager is not exposed. Is that a separate bug?

**Comment by christianpoitras** [comment] 2016-09-30 11:15
This happens because if the SqlSessionManager is not exposed, Guice has to instantiate de service implementation in the private module to allow the injection of the SqlSessionManager field.

By exposing the SqlSessionManager instance, the SqlSessionManager is now available to the private's module parent (the main injector in this case). So Guice will instantiate the service from the private's module parent to make it available to the widest amount of classes.

**Comment by christianpoitras** [comment] 2016-11-28 13:29
Since this issue is old and seems invalid, I am closing it.

**Closed by christianpoitras** 2016-11-28 13:29 UTC
