### ISSUE TITLE
@Transactional doesn't work when annotated on default method

### ISSUE THREAD

**Issue by RobertoUa** [mybatis/guice#120] opened 2017-10-25 19:11 UTC
I have to create a service and inject a mapper into it. It's too complicated when I need to add the annotation only on one method. Creating a default method in mapper interface is much simpler.

**Comment by christianpoitras** [comment] 2017-10-26 16:15
Hi. I am not sure what you are asking for.
Can you give me an example or a unit test that shows what you are trying to do?

**Comment by RobertoUa** [comment] 2017-10-27 08:29
Sure. I was talking about interface default method in java 8. Something like this.
I actually use it a bit differently, I don't throw exception, but I do wanna use multiple sql queries in one method.
```
public interface UserMapper {

    void insertUser(@Param("username") String username);

    User selectUser(@Param("username") String username);

    @Transactional
    default void insertUserCheck(String username) {
        if (selectUser(username) != null) {
            throw new RuntimeException("User " + username + " exists");
        }
        insertUser(username);
    }
}
```

**Comment by RobertoUa** [comment] 2017-10-27 08:33
like here https://github.com/mybatis/guice/blob/master/src/test/java/org/mybatis/guice/sample/service/FooServiceDaoImpl.java
I don't want to create FooServiceDaoImpl and use UserDao there. It's too complicated (when all I need is one transactional method)

**Comment by christianpoitras** [comment] 2018-07-06 18:23
My hypothesis is that it is a problem with Guice. We don't do anything other than register the interceptor and it seems Guice is skipping default methods.

**Comment by christianpoitras** [comment] 2018-07-09 15:13
It seems to require Guice version 4.2 to work. They added a unit test for this in and the latest date is September 2016.
https://github.com/google/guice/blob/master/jdk8-tests/test/com/google/inject/jdk8/DefaultMethodInterceptionTest.java

Did you try with Guice version 4.2?

**Comment by RobertoUa** [comment] 2018-07-09 16:18
I see. Thanks for the info!
Unfortunately, I'm stuck with 3.0 :(

**Comment by christianpoitras** [comment] 2018-07-10 15:50
I am marking it as won't fix for now.
If the problem is still present while using Guice 4.2, please provide me with a test case and I will look into it.

**Closed** 2018-07-10 15:51 UTC
Labels: wontfix
